import { ConnectButton } from "@rainbow-me/rainbowkit";
import type { NextPage } from "next";
import Head from "next/head";
import { Mint } from "../components/mint/Mint";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>RainbowKit App</title>
        <meta
          name="description"
          content="Generated by @rainbow-me/create-rainbowkit"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <ConnectButton />
        <Mint />
        <h1 className={styles.title}>
          Mint your <a href="">NFT</a>
        </h1>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://twitter.com/tomiioliver"
          target="_blank"
          rel="noopener noreferrer"
        >
          Made with ❤️ by Tomi204
        </a>
      </footer>
    </div>
  );
};

export default Home;
