import { ConnectButton } from "@rainbow-me/rainbowkit";
import type { NextPage } from "next";
import Head from "next/head";
import { Mint } from "../components/mint/Mint";
import styles from "../styles/Home.module.css";
import { useAddRecentTransaction } from "@rainbow-me/rainbowkit";
import { chain } from "wagmi";
import { MetaData } from "../components/mint/Metadata";

const Home: NextPage = () => {
  const addRecentTransaction = useAddRecentTransaction();

  return (
    <div className={styles.container}>
      <Head>
        <title>Mint site Tomi204</title>
        <meta
          name="description"
          content="Generated by @rainbow-me/create-rainbowkit"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.navbar}>
        <ConnectButton />
      </div>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Mint your{" "}
          <a href="https://testnets.opensea.io/es/assets/goerli/0xb7004ed1f06282995ae210b5c00d8d75733fc095/0">
            NFT
          </a>
        </h1>
        <MetaData />
        <Mint />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://twitter.com/tomiioliver"
          target="_blank"
          rel="noopener noreferrer"
        >
          Made with ❤️ by Tomi204
        </a>
      </footer>
    </div>
  );
};

export default Home;
